### PR TITLE
Update add command

### PR DESCRIPTION
**Pull request by nyannnnnnn**

### CODE REVIEW

**Review by evilmtv — CHANGES_REQUESTED** [review]
1. remove .classpath for the commit because the added lines are for your local changes only.
2. don't change BackupCommand.java and DirectoryCommand.java, remove them from your commit.
3. Is your collating comment wrong? It should be something like '//@@author A0147944U' right? For example you typed it in a comment block in TimeParserResult.java

**Review by evilmtv — COMMENTED** [review]
You've reverted Deadline.java , EndTime.java , StartTime.java back to the previous broken regex that accepts all input. I'll work on it once I've read up on how the new parser works!

**Comment by nyannnnnnn** [comment]
I don't know why i cannot pass the traivs

**Comment by nyannnnnnn** [comment]
I have changed all the requests

**Review by evilmtv — APPROVED** [review]

**Comment by evilmtv** [comment]
Resolves #46 
Resolves #51

**Pull request merged**
